# Generated by Django 6.1 on 2026-09-07 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name_arabic', models.CharField(max_length=100)),
                ('name_uz', models.CharField(max_length=100)),
                ('name_english', models.CharField(blank=True, max_length=100)),
                ('revelation_place', models.CharField(default='makkah', max_length=50)),
                ('total_ayahs', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('current_surah_number', models.PositiveIntegerField(default=1)),
                ('current_ayah_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_surah', models.PositiveIntegerField()),
                ('number_global', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('text_arabic_tajweed', models.TextField(help_text='Uthmanic script with Tajweed diacritics')),
                ('text_arabic_clean', models.TextField(help_text='Clean text without diacritics for search')),
                ('text_translit', models.TextField(blank=True, default='', help_text='Latin transliteration')),
                ('text_translation_uz', models.TextField(blank=True, default='', help_text='Uzbek translation')),
                ('official_audio_url', models.URLField(blank=True, default='', max_length=500)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayahs', to='api.surah')),
            ],
            options={
                'ordering': ['surah', 'number_in_surah'],
                'unique_together': {('surah', 'number_in_surah')},
            },
        ),
        migrations.CreateModel(
            name='RecitationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='recitations/%Y/%m/%d/')),
                ('score', models.IntegerField(default=0, help_text='Accuracy score (0-100)')),
                ('word_level_result', models.JSONField(default=list, help_text='Word by word evaluation array')),
                ('overall_feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.ayah')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.telegramuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('attempts_count', models.PositiveIntegerField(default=1)),
                ('best_score', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ayah')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.surah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='api.telegramuser')),
            ],
            options={
                'ordering': ['surah', 'ayah'],
                'unique_together': {('user', 'ayah')},
            },
        ),
    ]
