# Generated by Django 6.1 on 2026-09-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Xabarnoma ichki nomi (admin uchun)', max_length=255)),
                ('message_text', models.TextField(help_text='Xabar matni (HTML formatida: <b>qalin</b>, <i>kursiv</i>, {name} shaxsiy ism)')),
                ('photo', models.ImageField(blank=True, help_text="Xabarga qo'shiladigan rasm (ixtiyoriy)", null=True, upload_to='broadcasts/%Y/%m/')),
                ('button_text', models.CharField(blank=True, default='', help_text='Inline tugma yozuvi (masalan: 📖 Tilovatni Boshlash)', max_length=100)),
                ('button_url', models.URLField(blank=True, default='', help_text='Tugma bosilganda ochiladigan havola', max_length=500)),
                ('target_audience', models.CharField(choices=[('all', 'Barcha foydalanuvchilar'), ('active', 'Faol qorilar (kamida 1 tilovat qilganlar)'), ('inactive', 'Hali tilovat topshirmaganlar')], default='all', help_text='Xabar kimlarga yetkazilsin?', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Qoralama (Yuborilmagan)'), ('sending', 'Yuborilmoqda...'), ('sent', 'Muvaffaqiyatli yuborildi'), ('failed', 'Xatolik bilan tugadi')], default='draft', max_length=20)),
                ('sent_count', models.PositiveIntegerField(default=0, help_text='Yetkazilganlar soni')),
                ('failed_count', models.PositiveIntegerField(default=0, help_text='Yetib bormaganlar soni')),
                ('error_summary', models.TextField(blank=True, default='', help_text='Xatolik tafsilotlari')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ommaviy Xabarnoma',
                'verbose_name_plural': 'Ommaviy Xabarnomalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
