# Generated by Django 6.1 on 2026-09-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_broadcastmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='selected_users',
            field=models.ManyToManyField(blank=True, help_text="Auditoriya 'Tanlangan aniq foydalanuvchilar' bo'lsa, xabar aynan shu foydalanuvchilarga yuboriladi.", related_name='targeted_broadcasts', to='api.telegramuser', verbose_name='Tanlangan foydalanuvchilar'),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='target_audience',
            field=models.CharField(choices=[('all', 'Barcha foydalanuvchilar'), ('active', 'Faol qorilar (kamida 1 tilovat qilganlar)'), ('inactive', 'Hali tilovat topshirmaganlar'), ('selected', 'Tanlangan aniq foydalanuvchilar')], default='all', help_text='Xabar kimlarga yetkazilsin?', max_length=20),
        ),
    ]
